-- MySQL Script generated by MySQL Workbench
-- Sun May  3 14:18:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Coloretto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Coloretto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Coloretto` DEFAULT CHARACTER SET utf8 ;
USE `Coloretto` ;

-- -----------------------------------------------------
-- Table `Coloretto`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Cards` (
  `idCard` INT NOT NULL,
  `name` VARCHAR(10) NULL,
  PRIMARY KEY (`idCard`))
ENGINE = InnoDB;

INSERT INTO `Cards` (idCard, name)
	VALUES(0, 'back'),
	(1, 'blauw'),
	(2, 'bruin'),
	(3, 'geel'),
	(4, 'grijs'),
	(5, 'groen'),
	(6, 'joker'),
	(7, 'oranje'),
	(8, 'roze'),
	(9, '+2');

-- -----------------------------------------------------
-- Table `Coloretto`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Players` (
  `idPlayer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `isNext` TINYINT(0) NOT NULL,
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idPlayer`),
  FOREIGN KEY (idGame) REFERENCES Decks(idGame))
ENGINE = InnoDB;

INSERT INTO `Players` (idPlayer, name, isNext, idGame)
	VALUES(0, 'Nicolas', 0, 0),
    (1, 'Manu', 0, 0),
    (2, 'Matheis', 1, 0),
    (3, 'Fons', 0, 0),
    (4, 'Glen', 0, 0);

CREATE TABLE IF NOT EXISTS `Coloretto`.`Highscores` (
	`name` VARCHAR(45) NOT NULL,
    `score` INT NOT NULL)
ENGINE = InnoDB;

INSERT INTO `Highscores` (name, score)
	VALUES('Nicolas', 30),
    ('Nicolas', 40),
    ('Fons', 35),
    ('Johannes', 20),
    ('Glen', 32);

-- -----------------------------------------------------
-- Table `Coloretto`.`Player/Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Players/Cards` (
  `idPlayer` INT NOT NULL,
  `idCard` INT NOT NULL,
  `amount` INT NOT NULL)
ENGINE = InnoDB;

INSERT INTO `Players/Cards` (idPlayer, idCard, amount)
	VALUES(0, 1, 5),
    (0, 2, 4),
    (1, 2, 3),
    (1, 3, 2),
    (2, 3, 1),
    (2, 3, 2),
    (3, 4, 2),
    (4, 4, 5)
;

-- -----------------------------------------------------
-- Table `Coloretto`.`Deck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Games` (
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idGame`))
ENGINE = InnoDB;

INSERT INTO `Games` (idGame)
	VALUES(0)
;

CREATE TABLE IF NOT EXISTS `Coloretto`.`Stacks` (
  `idStack` INT NOT NULL,
  `isTaken` TINYINT(0) NOT NULL,
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idStack`),
  FOREIGN KEY (idGame) REFERENCES Games(idGame))
ENGINE = InnoDB;

INSERT INTO `Stacks` (idStack, isTaken, idGame)
	VALUES(0, 0, 0),
    (1, 0, 0),
    (2, 1, 0),
    (3, 0, 0),
    (4, 1, 0);

-- -----------------------------------------------------
-- Table `Coloretto`.`Stack/Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Stacks/Cards` (
  `idStack` INT NOT NULL,
  `idCard` INT NOT NULL,
  `amount` INT NOT NULL)
ENGINE = InnoDB;

INSERT INTO `Stacks/Cards` (idStack, idCard, amount)
	VALUES(0, 1, 2),
    (0, 2, 1),
    (1, 3, 3),
    (3, 5, 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
