-- MySQL Script generated by MySQL Workbench
-- Sun May  3 14:18:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Coloretto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Coloretto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Coloretto` DEFAULT CHARACTER SET utf8 ;
USE `Coloretto` ;

-- -----------------------------------------------------
-- Table `Coloretto`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Card` (
  `idCard` INT NOT NULL,
  `name` VARCHAR(10) NULL,
  PRIMARY KEY (`idCard`))
ENGINE = InnoDB;

INSERT INTO `Card` (idCard, name)
	VALUES(0, 'back'),
	(1, 'blauw'),
	(2, 'bruin'),
	(3, 'geel'),
	(4, 'grijs'),
	(5, 'groen'),
	(6, 'joker'),
	(7, 'oranje'),
	(8, 'roze')
;


-- -----------------------------------------------------
-- Table `Coloretto`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Player` (
  `idPlayer` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlayer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coloretto`.`Player/Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Player/Card` (
  `idPlayer` INT NOT NULL,
  `idCard` INT NOT NULL,
  `amount` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coloretto`.`Deck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Deck` (
  `idDeck` INT NOT NULL,
  PRIMARY KEY (`idDeck`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coloretto`.`Deck/Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Deck/Card` (
  `idDeck` INT NOT NULL,
  `idCard` INT NOT NULL,
  `amount` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coloretto`.`Stack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Stack` (
  `idStack` INT NOT NULL,
  `isTaken` TINYINT(0) NOT NULL,
  PRIMARY KEY (`idStack`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coloretto`.`Stack/Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Stack/Card` (
  `idStack` INT NOT NULL,
  `idCard` INT NOT NULL,
  `amount` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
