-- MySQL Script generated by MySQL Workbench
-- Sun May  3 14:18:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Coloretto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Coloretto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Coloretto` DEFAULT CHARACTER SET utf8 ;
USE `Coloretto` ;

-- -----------------------------------------------------
-- Table `Coloretto`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Card` (
  `idCard` INT NOT NULL,
  `name` VARCHAR(10) NULL,
  PRIMARY KEY (`idCard`))
ENGINE = InnoDB;

INSERT INTO `Card` (idCard, name)
	VALUES(0, 'back'),
	(1, 'blauw'),
	(2, 'bruin'),
	(3, 'geel'),
	(4, 'grijs'),
	(5, 'groen'),
	(6, 'joker'),
	(7, 'oranje'),
	(8, 'roze'),
	(9, '+2');

-- -----------------------------------------------------
-- Table `Coloretto`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Player` (
  `idPlayer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `isNext` TINYINT(0) NOT NULL,
  PRIMARY KEY (`idPlayer`))
ENGINE = InnoDB;

INSERT INTO `Player` (idPlayer, name, isNext)
	VALUES(0, 'Nicolas', 0),
    (1, 'Manu', 0),
    (2, 'Matheis', 1),
    (3, 'Fons', 0),
    (4, 'Glen', 0);

-- -----------------------------------------------------
-- Table `Coloretto`.`Player/Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Player/Card` (
  `idPlayer` INT NOT NULL,
  `idCard` INT NOT NULL,
  `amount` INT NOT NULL)
ENGINE = InnoDB;

INSERT INTO `Player/Card` (idPlayer, idCard, amount)
	VALUES(0, 1, 5),
    (0, 2, 4),
    (1, 2, 3),
    (1, 3, 2),
    (2, 3, 1),
    (2, 3, 2),
    (3, 4, 2),
    (4, 4, 5)
;

-- -----------------------------------------------------
-- Table `Coloretto`.`Deck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Deck` (
  `idDeck` INT NOT NULL,
  PRIMARY KEY (`idDeck`))
ENGINE = InnoDB;

INSERT INTO `Deck` (idDeck)
	VALUES(0)
;

-- -----------------------------------------------------
-- Table `Coloretto`.`Deck/Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Deck/Card` (
  `idDeck` INT NOT NULL,
  `idCard` INT NOT NULL,
  `amount` INT NOT NULL)
ENGINE = InnoDB;

INSERT INTO `Deck/Card` (idDeck, idCard, amount)
	VALUES(0, 1, 7),
    (0, 2, 7),
    (0, 3, 7),
    (0, 4, 7),
    (0, 5, 7),
    (0, 6, 3),
    (0, 7, 7),
    (0, 8, 10)
;

-- -----------------------------------------------------
-- Table `Coloretto`.`Stack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Stack` (
  `idStack` INT NOT NULL,
  `isTaken` TINYINT(0) NOT NULL,
  PRIMARY KEY (`idStack`))
ENGINE = InnoDB;

INSERT INTO `Stack` (idStack, isTaken)
	VALUES(0, 0),
    (1, 0),
    (2, 1),
    (3, 0),
    (4, 1);

-- -----------------------------------------------------
-- Table `Coloretto`.`Stack/Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coloretto`.`Stack/Card` (
  `idStack` INT NOT NULL,
  `idCard` INT NOT NULL,
  `amount` INT NOT NULL)
ENGINE = InnoDB;

INSERT INTO `Stack/Card` (idStack, idCard, amount)
	VALUES(0, 1, 2),
    (0, 2, 1),
    (1, 3, 3),
    (3, 5, 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
